# Site settings

title: Cristian Perez Brokate
description: > # this means to ignore newlines until "baseurl:"
  I use data science tools to process multiple source of data and build robust data process pipelines.
  I build web applications with modern frontend javascript frameworks.
  I'm also in charge of IT management for large compute servers.
  In my free time I build IoT applications.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cristianpb.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: https://twitter.com/cris_perez_b
# Needed by jekyll-seo-tag
twitter: 
  username: cris_perez_b
logo: '/assets/img/avatar.png' 
linkedin_username: cristianperezbrokate
github_username:  cristianpb
researchgate_username:  Cristian_Perez_Brokate
social:
  name: Cristian Perez Brokate
  links:
    - https://twitter.com/cris_perez_b
    - https://www.linkedin.com/in/cristianperezbrokate
    - https://github.com/cristianpb
    - https://scholar.google.com/citations?hl=en&user=rIdjCp0AAAAJ
    - https://www.researchgate.net/profile/Cristian_Perez_Brokate
    - https://www.kaggle.com/cristianpb
author:
  name: Cristian Perez Brokate
  github: cristianpb
  medium: "@cristianpb"
  twitter: cris_perez_b
  linkedin: cristianperezbrokate
  kaggle: cristianpb

google_analytics: G-GHSXP90EV3
google_site_verification: dadHYln91lNA-p2JDYCrivQ6etkGJeqk1Dz1GpshKk0

# algolia search
algolia:
  application_id: 'Z1GMX6PWB9'
  index_name: cristianpb
  files_to_exclude:
    - jekyll_collections/_blog/*.html
    - jekyll_collections/_drafts/*.html
    - jekyll_collections/_iframes/*.html
    - jekyll_collections/_pages/*.html
    - jekyll_collections/_api/github-pages.html

# Color the browser elements #
color-browser: "#247da6"
apple-status-bar-style: "black-translucent"
 
# Build settings
sass:
    style: compressed
markdown: kramdown
kramdown:
  parse_block_html: true
plugins:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

collections_dir: jekyll_collections
collections:
  blog:
    output: true
  iframes:
    output: true
  pages:
    output: true
  api:
    output: true

defaults:
    - {scope: {type: blog}, values: {layout: page, permalink: '/blog/:title'}}
    - {scope: {type: iframes}, values: {layout: iframe, sitemap: false}}
    - {scope: {type: posts}, values: {layout: post, permalink: '/blog/:title', animation: true, bind: true}}
    - {scope: {path: "", layout: default}, values: {image: {
      path: '/assets/img/avatar.png', width: 200, height: 200}}}

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.md
  - node_modules
  - npm-debug.log
  - gulpfile.js
  - package.json
  - package-lock.json

feed:
  collections:
    posts:
      path: feed.xml
