---
name: Github CI

on: [push]

env:
  ruby-version: "3.1"
  node-version: 20

jobs:
  job-amp:
    name: Test AMP format

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.ruby-version }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
      - name: Install node requirements
        run: npm ci
      - name: Install ruby dependencies
        run: |
          sed -i "/\b\(redirect\)\b/d" Gemfile
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Build css
        run: npm run css:build
      - name: Build HTML
        run: npm run build
      - name: Test AMP support
        run: npm run test
  job-algolia:
    name: Algolia push records
    needs: job-amp

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.ruby-version }}
      - name: Install ruby dependencies
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Push algolia records
        if: success() && github.ref == 'refs/heads/master'
        run: bundle exec jekyll algolia
        env:
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
  job-html:
    name: Test html consistency
    needs: job-amp

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.ruby-version }}
      - name: Install ruby dependencies
        run: |
          sed -i "/\b\(redirect\)\b/d" Gemfile
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - run: npm run build
      - name: Test html
        run: |
          gem install html-proofer
          htmlproofer --ignore-urls "/www.linkedin.com/,/twitter.com/,/www.researchgate.net/,/www.sciencedirect.com/,/www.arduino.cc/,/www.velib-metropole.fr/,/herokuapp.com/,/www.tandfonline.com/" --ignore-missing-alt --allow-missing-href --ignore-status-codes "0"  ./_site
